approve_by_comment: true
author_approval: ignored
approve_regex: '(?i)^(approved|looks good|:shipit:|:\+1:)'
reject_regex: '(?i)^Rejected'
reset_on_push: false
always_pending:
  labels:
  - progress
  explanation: 'This PR is a work in progress'
reviewers:
  - name: querydsl team
    teams:
    -  developers
    required: 1
